# -*- coding: utf-8 -*-
"""multivariable_Matplotlib3D.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1woqTvM1E4wk4z5n-Z_ia4fKr2bgBEjYN
"""

import numpy as np
import matplotlib.pyplot as plt

f = lambda x, y: x**4+y**4
x = np.linspace(-2,2,100)
y = np.linspace(-2,2,100)
X, Y = np.meshgrid(x,y)
F = f(X,Y)

plt.contour(X,Y,F,200
          )
plt.show()

import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from matplotlib import cm

f = lambda x, y: x**4+y**4
x = np.linspace(-2,2,50)
y = np.linspace(-2,2,50)
X, Y = np.meshgrid(x,y)
F = f(X,Y)

fig = plt.figure(figsize = (12,8))
ax = fig.gca(projection = '3d')
ax.plot_surface(X, Y, F, cmap=cm.coolwarm)
plt.show()

import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from matplotlib import cm

f = lambda x, y: x**4+y**4
x = np.linspace(-2,2,50)
y = np.linspace(-2,2,50)
X, Y = np.meshgrid(x,y)
F = f(X,Y)

def  plotter(E,A):
  fig = plt.figure(figsize = (12,8))
  ax = fig.gca(projection = '3d')
  ax.plot_surface(X, Y, F, cmap=cm.coolwarm)
  ax.view_init(elev=E,azim=A)
  plt.show()

plotter(30,15)

from ipywidgets import interactive
iplot = interactive(plotter,
                    E = (-90,90,5),
                    A = (-90,90,5)
                    )
iplot

